In [6]:
import numpy as np

In [7]:
data = np.loadtxt("populations.txt")

In [8]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [9]:
year, hares, lynxes, carrots = data.T # columns to variables

In [10]:
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [11]:
# The mean population over time
population = data[:, 1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [12]:
# standard deviation
population.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [13]:
# which species has the highest population each year

np.argmax(population, axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [16]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [17]:
a = np.tile(np.arange(0, 40, 10), (3, 2))


In [18]:
a

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [19]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [20]:
a = a.T
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [21]:
a = np.tile(np.arange(0, 40, 10), (3, 2))
a 

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [22]:
a = a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [23]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [24]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [25]:
a + b 

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [26]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [27]:
a = a[:, np.newaxis] # adds a new axis ---> 2D array
a.shape 

(4, 1)

In [28]:
a 

array([[ 0],
       [10],
       [20],
       [30]])

In [29]:
b

array([0, 1, 2])

In [30]:
a + b 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [31]:
b.shape

(3,)

In [40]:
# Flattening

a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.ravel())

[1 2 3 4 5 6]


In [33]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [43]:
# Reshaping - The Inverse Operation to flattening
print(a.shape)

(2, 3)


In [44]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [46]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b[0, 0] = 500
a 

array([[500,   2,   3],
       [  4,   5,   6]])

In [50]:
# Note and Beaware : Reshare may also return a copy

a = np.zeros((3, 2))
a 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [51]:
a.T

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
a.T.reshape(3*2)

array([0., 0., 0., 0., 0., 0.])

In [53]:
b = a.T.reshape(3*2)

In [54]:
b

array([0., 0., 0., 0., 0., 0.])

In [55]:
b[0] = 50

In [56]:
b

array([50.,  0.,  0.,  0.,  0.,  0.])

In [57]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [58]:
# Adding a Dimension
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [59]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [60]:
# Dimension Shuffling

a = np.arange(4*3*2)
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [61]:
a = a.reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [62]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [63]:
a[0, 2, 1]

5

In [64]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [65]:
a.resize((8,))
a

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [66]:
d = np.arange(4)
d.resize((8,))
d

array([0, 1, 2, 3, 0, 0, 0, 0])

In [67]:
p = d
p.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [68]:
# Sorting Data along the axis
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis = 1)
b


array([[4, 5, 6],
       [2, 2, 3]])

In [69]:
a.sort(axis=1) # in-place sorting

In [70]:
a

array([[4, 5, 6],
       [2, 2, 3]])

In [72]:
# Sorting with fancy Indexing
a = np.array([4, 3, 1, 2])

In [73]:
a

array([4, 3, 1, 2])

In [74]:
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [75]:
a[j]

array([1, 2, 3, 4])